### ISSUE TITLE
ATLAS review - directory structure

### ISSUE THREAD

**Issue by jesusff** [IPCC-WG1/Atlas#10]
I find the structure OK. Just the `man` directory is a bit odd. I'm not sure of the origin of this directory name. This is a standard directory name for Unix man pages. However, it contains some instructions on the Atlas Hub, along with coastline data files and some images of the reference regions and grids. A clearer name could be found for this directory, or the contents moved to the existing ones (e.g. to reference-regions, reference-grids, ...).

**Comment by huard** [comment]
Also, the `man` repo lacks a README.

**Comment by jesusff** [comment]
There is a new structure (f494de8) where the man/ directory has been removed and the contents moved to more appropriate places.
