### ISSUE TITLE
Issues with getting timeseries

### ISSUE THREAD

**Issue by aschurer** [IPCC-WG1/Atlas#102]
Hi,
I have been using the atlas for a tutorial session (01/10/2024) but me and all the students ran into many problems producing time series.
This affected a large proportion of the things that we tried.

This is an example
https://interactive-atlas.ipcc.ch/permalink/efV7Swbi

![Capture](https://github.com/user-attachments/assets/44df9220-c9d4-4389-a6b4-46d060a8b970)

The problems aren't always systematic with certain timeseries working for some students and not others and could work one moment and then not work the next.

Is this a known problem?

Can you suggest how to resolve it, as I would like to continue using this fantastic resource for teaching.

Thanks
Andrew

**Comment by jesusff** [comment]
Thank you for reporting. Unfortunately, some resources that deal with time series were down until last Wed. This should work fine now, and generally in the future for your lessons 🙂
