### ISSUE TITLE
ATLAS review - more information in the README

### ISSUE THREAD

**Issue by matteodefelice** [IPCC-WG1/Atlas#11]
This repository is a timely contribution to the need of a transparent and reproducible science and evidence-informed policy making. To this end, I think we should expect many different types of users, not only climate scientists but in general data practitioners and scientists from other disciplines. 
Then I think the README should be more informative and providing details on:

- What can be found in each directory (I agree with https://github.com/IPCC-WG1/Atlas/issues/9 )
- The requirements to run the code: R, which version? On which platforms? And Jupyter? How to have R into Jupyter? Is Anaconda needed?

**Comment by jesusff** [comment]
Thank you for the review. The main README has been modified to include further details on the contents and the requirements to run the contents. Most of the information on versions and technical how-to details has been included as links.
