### ISSUE TITLE
ATLAS Review - metadata for aggregated dataset

### ISSUE THREAD

**Issue by matteodefelice** [IPCC-WG1/Atlas#12]
The CSV files in the `aggregated-datasets/data` are probably the most important for the non (climate) data scientists, in the end for many applications a time-series is enough to produce meaningful insights. To this end, I would add other fields in the metadata provided in the header of the CSV files:
- Name of model 
- Emission scenario
- Full name of the variable and *unit*
- Reference to the list of the regions

In my opinion, with those info, the files might have more value for many users.

**Comment by jesusff** [comment]
Thank you for the review. We added this and other additional information in the new CSV files.
