### ISSUE TITLE
ATLAS Review - reference-regions README

### ISSUE THREAD

**Issue by aspinuso** [IPCC-WG1/Atlas#14]
in the README
https://github.com/IPCC-WG1/Atlas/blob/master/reference-regions/README.md 

The link to the AtlasHub-inventory gives 404. Does it exist/require special **A**ccess rights? if yes it should be explained how to get that. How is this related to the The Atlas Hub mentioned in the review guidelines? (https://hub.ipcc.ifca.es)

**Comment by jesusff** [comment]
Thank you for the review. This referred to the Atlas inventory (currently under folder `inventory`). The link has been fixed.
