### ISSUE TITLE
ATLAS review - Code licenses

### ISSUE THREAD

**Issue by huard** [IPCC-WG1/Atlas#15]
Some scripts have a GPL license in the headers. Can these be removed since there is already a license file in the top directory ?
Also, can the scripts be made available under CC-BY ?

**Comment by hot007** [comment]
Does it need to be CC-BY rather than GPL?
Overall [Licence file ](https://github.com/IPCC-WG1/Atlas/blob/master/LICENSE.md) indicates all scripts are GPL - but I do agree that consistency is important, either all headers should contain the licence or none.

**Comment by jesusff** [comment]
Thank you for the review. We finally made the scripts CC BY 4.0 as the rest of the contents of the repo. This makes the license cleaner. We just had to notice the extra Share Alike restriction in CMIP6-derived products.
Regarding the license headers, they are now consistently included in all scripts and notebooks, just in case they get separated from the rest of the repository.
