### ISSUE TITLE
ATLAS review - Additional information

### ISSUE THREAD

**Issue by huard** [IPCC-WG1/Atlas#20]
- [ ] README: Please add a little more info on what is found in each directory. For example, how is the grid resolution computed? What are the stripes plot for, etc ?
- [ ] stripes-plots/README.md: Just a title, no content.

**Comment by jesusff** [comment]
Thank you for your review. The contents of the additional information folder have been relocated in other folders in the new directory structure. In general, all README files have been improved to detail the contents of their corresponding folder. In particular, the stripes-plots folder/script has been converted into a notebook now: https://github.com/IPCC-WG1/Atlas/blob/devel/notebooks/stripes-plots_R.ipynb
