### ISSUE TITLE
ATLAS review - ESGF-inventory

### ISSUE THREAD

**Issue by huard** [IPCC-WG1/Atlas#21]
This directory is probably the most obscure one. The README is pretty thin and overall, it feels very much like internal stuff. Not clear exactly how to review this.

**Comment by jesusff** [comment]
Thanks for the review. This directory was removed from the new structure (f494de8). As you mention, it was useful internally, while planning the Atlas dataset, but now the only inventory that remains is the final `inventory` of data used in the Atlas.
