### ISSUE TITLE
ATLAS Review - ATLAS-inventory

### ISSUE THREAD

**Issue by aspinuso** [IPCC-WG1/Atlas#23]
The Review Guiding document specifies that the datasets mentioned in the inventory support provenance. Could the inventory include a link to the dataset and/or especially to the provenance records associated with it, in a way that this could be validated?

**Comment by jesusff** [comment]
Thank you for your review. The inventory folders include now links to provenance records (handle.net links) when available and ESGF search URLs resolving the corresponding dataset, to ensure that the datasets and corresponding metadata can be easily reached. This information is provided in the README file, which renders an HTML table with the links. See e.g. https://github.com/IPCC-WG1/Atlas/tree/56246cbba76d9d463b2756401101ac9dfa43f4bb/inventory/CMIP6
