### ISSUE TITLE
ATLAS Review - ESGF Inventory DOIs

### ISSUE THREAD

**Issue by aspinuso** [IPCC-WG1/Atlas#24]
CMIP6 datasets are usually provided with a DOI, which is returned by the ESGF search service. 

In order to support FAIRness, could the DOIs be resolved and the landing page stored in the inventory? Is this maybe already implemented in the Interactive Atlas tool?

For instance, taking as example the dataset

CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r1i1p1f1.Amon.gr

The associated DOI would be 

doi:10.22033/ESGF/CMIP6.4700

which resolves to the landing page which contains many of information on the model, such as its parametrisation, characteristic, execution, attribution (provenance).

https://cera-www.dkrz.de/WDCC/ui/cerasearch/cmip6?input=CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical

General question: Is there any higher granularity supported for CMIP6 DOIs? For instance until the variable?

**Comment by jesusff** [comment]
Thank you for your review. DOIs are not available for all datasets in the repository and, as you mention, the granularity of those entries does not go down to the variable. We opted for either handles or ESGF search URLs, which provide a direct link to the corresponding variables used. See also #23

**Comment by jesusff** [comment]
Sorry, I misunderstood your original question, which referred to the ESGF-inventory folder. This inventory was updated periodically for internal use and has been removed for the final, frozen version of the repository. My comments above referred to the Atlas-inventory (now, just inventory) which now incorporates links to the ESGF search and handle when available.
