### ISSUE TITLE
ATLAS Review - Consolidated

### ISSUE THREAD

**Issue by IrynaRozum** [IPCC-WG1/Atlas#28]
First, this is a great project and will come very useful to many researchers.
Interactive web http://ipcc-atlas.ifca.es : time series graphs have many lines and shades but no legends saying what they are, adding legends will greatly improve user experience.
Git Warming levels:  Some guide explaining how to interpret tables would help someone who is just starting with the subject.
Git Scripts:   Codes are well written with comments, so easy to read. A little more information (reference literature/papers) in the README.md about methods used in calculations would be useful.

**Comment by jesusff** [comment]
Thank you for your review. Your comment about the Interactive Atlas has been handled by the IA development team and has been taken into account in the final design of the IA. Regarding the repository, all README's have been extended to better describe the contents of the folders. Scripts and notebooks have also been better documented, including literature where appropriate.
