### ISSUE TITLE
ATLAS Review - Home page

### ISSUE THREAD

**Issue by rmanzanas** [IPCC-WG1/Atlas#30]
Although find the general structure of the repo is OK, the main README (at the root directory level) may not be really descriptive of the contents that are actually hosted. Considering this is the first impression a user gets when he/she lands on the repo, it may be worth to polish a bit this page. A simple improvement would be to include at this level one small paragraph briefly describing what is included in each directoy (aggregated-datasets, reference-grids, etc.). I don't see it's a problem to have this information duplicated in the corresponding README of each directory.

**Comment by jesusff** [comment]
Thank you for the review. The main README has been updated (f494de8) and, in particular, a table of contents has been added to briefly explain the contents of each directory.
