### ISSUE TITLE
ATLAS Review - Terminology homogenization

### ISSUE THREAD

**Issue by rmanzanas** [IPCC-WG1/Atlas#31]
This is a minor comment, but it'd be nice to carefully check the terminology used along the repo for the sake of consistency. For instance, the terms "Climate Change Atlas", "ATLAS" (capital letters), "Atlas" (small letters) could be easily homogeneized.

**Comment by jesusff** [comment]
Thank you for the review. Yes, this was mentioned also in #35. We consistently renamed (f494de8) all ATLAS instances to Atlas.
