### ISSUE TITLE
ATLAS Review - ESGF-inventory directory

### ISSUE THREAD

**Issue by rmanzanas** [IPCC-WG1/Atlas#32]
The "esgf-utils @ 30edcfb", "publisher @ 0e4b1bb" and "tds-content @ b6f5dc3" directories seem to be mostly for internal use, I'm not sure if it's worth to keep them in the repo.

**Comment by jesusff** [comment]
Thanks for the review. Yes, the full `ESGF-inventory` has been removed from the new repository structure (f494de8). It was useful during the development stage, but it could be misleading for the users of the repository when frozen.
