### ISSUE TITLE
ATLAS Review - Observations

### ISSUE THREAD

**Issue by rmanzanas** [IPCC-WG1/Atlas#34]
This is more a question/curiosity than a comment: Why does the repo focus only on model (CMIP5/6, CORDEX) simulations and does not provide access to aggregated observations? Having these data would be very useful for many users.

**Comment by jesusff** [comment]
Thank you for the review. There are now observations available in the repository in the same format as the rest of the model data. In particular, the W5E5 dataset (Lange, 2019 https://doi.org/10.5880/PIK.2019.023) has been aggregated regionally (https://github.com/IPCC-WG1/Atlas/tree/devel/datasets-aggregated-regionally/data/OBSERVATIONS). Some notebooks (linear-trends, bias-adjustment) also make use of observations.
