### ISSUE TITLE
ATLAS review

### ISSUE THREAD

**Issue by DamienIrving** [IPCC-WG1/Atlas#4]
Thanks for the invitation to participate in the IPCC AR6 WGI Atlas FAIR Review - it's exciting to see the IPCC get involved in the open/reproducible science space.

My feedback relates primarily to the issue of orienting readers of the Atlas to the information/metadata available to them. From the README in the root directory and the READMEs in each sub directory it is possible to figure out everything that's available, but I think the main README in the root directory would benefit from a quick summary/overview. Something along the lines of:

For any data visualisation in the Interactive Atlas or Atlas Chapter, you can get the following information/metadata from the various directories in this repository:  
- `aggregated-datasets/`: the corresponding data (i.e. the values shown in the visualisation)
- `scripts/`: the code that generated the visualisation 
- `ATLAS-inventory/`: a list of the models/runs (and their version number) shown in the visualisation  
- `reference-grids/`: details of the common ensemble grid that the models were interpolated to 
- `reference-regions/`: details of the region boundaries
  
If you'd like to dig further into the data on your own, you can also access:
- `man/`: a cloud environment (the "Atlas Hub") to analyse the data
- `notebook/`: user friendly descriptions (in Python and R) of how to work with the data

Other information included included in the repository includes:
- `warming_levels/`: data for particular warming levels as opposed to time slices (not shown in the Atlas)
- `ESGF_inventory/`: a list of all the model data available on the ESGF (this is really for planning purposes only)

**Comment by jesusff** [comment]
In this line, mentions of particular directories in the README text (currently in quotes and boldface) could be converted into links that carry the reader directly to that directory (i.e. to other rendered README file which, in turn, includes additional references -links- to other directories). In this way, the reader could easily browse the repo without going back and forth from the READMEs to the code browser.

**Comment by jesusff** [comment]
Thanks for the review. There is now a new structure, but we followed the recommendation of orienting the readers from the main README, providing brief descriptions of the contents of each directory (f494de8). There is still work to do in the main README (e.g. regarding the Atlas Hub), but I think we can close this issue.
