### ISSUE TITLE
Default selection of scenario

### ISSUE THREAD

**Issue by astroleo** [IPCC-WG1/Atlas#42]
When entering the interactive atlas / regional information, the default scenario that is selected is the "worst-case" scenario SS5 8.5, which is unlikely, as far as I know. Wouldn't it be better to select, by default, the most likely scenario, rather than the worst case one?

**Comment by jesusff** [comment]
Thank you for your feedback. Please, note that the map is computed using SSP5-8.5, but it represents the regional response to a Global Warming Level of 2 C. Therefore, the SSP is irrelevant for the results shown. SSP5-8.5 only guarantees that all models contribute to the results shown. You can change yourself the scenario and see that the picture hardly changes.
