### ISSUE TITLE
dymanic scale at left side does not coincide with location selected by map..see tx40 anywhere in N america

### ISSUE THREAD

**Issue by David-Levinthal** [IPCC-WG1/Atlas#43]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**
the dynamic sliding scale at the left of the display does not correspond to where the mouse is pointing

**To Reproduce**

Write below the steps to reproduce the problem:

1. zoom in to N america
2. set variable to TX40
3. set time period to medium future
4  float mouse of dark red areas (texas) or NE US (all greyed out)..the number of days above C40 is higher in NE (~15-20) than dark red (where scale sits around 10)
**Expected behavior**
I would say that was obvious
:-)

**Screenshots**

**Desktop (please complete the following information):**

windows 10 and Firefox browser
**Additional context**

**Comment by jesusff** [comment]
Thank you for reporting. This has been solved in the new Interactive Atlas version, to be released on Sep 27th
