### ISSUE TITLE
Guided tour help for time series tab incorrectly positioned

### ISSUE THREAD

**Issue by vrboten** [IPCC-WG1/Atlas#44]
**The guided tour help for Time Series is incorrectly positioned and the 'Time Series' tab isn't highlighted**

When taking the tour through the atlas a modal window (rather a layer) appears containing a help message explaining a UI element of the atlas. In all cases, the UI element is highlighted, except for the 'Time Scale' tab.

The respective help message appears in the middle of the screen not next to the 'Time Series' tab'

**To Reproduce**

Write below the steps to reproduce the problem:

1. Launch the atlas
2. On the world map click on a region or click the ''Select all regions' icon:
 - The guided tour for the lower visualization types appears
3. Click 'Next' until you get to the 'Time Series' tab in the lower third of the atlas' window

**Expected behavior**

The blue help message should appear next to the Time Series tab, and the latter should be highlighted, like it is for other tabs. Screenshot shows how it is for the 'GWL Plot' tab.

**Screenshots**
Issue: ![2021-08-09 17 39 25 interactive-atlas ipcc ch c5f5b8a4ffe4](https://user-images.githubusercontent.com/28765181/128735411-e9663da4-34de-4a8d-81ea-479f3016d6eb.jpg)

Expected appearance (but as an example for 'GWL Plot'):
![2021-08-09 17 52 38 interactive-atlas ipcc ch 1aaa5acb648d](https://user-images.githubusercontent.com/28765181/128736473-1597da4a-c9c4-4df7-8a31-b26fae0cd19b.jpg)

**Desktop:**

- OS: Windows 64-bit
 - Browser: Vivaldi
 - Version 3.6.2165.36

**Comment by jesusff** [comment]
Thank you for reporting. This has been solved in the new Interactive Atlas version, to be released on Sep 27th
