### ISSUE TITLE
Continent outlines on Pacific-centric Robinson map do not print correctly to PNG

### ISSUE THREAD

**Issue by georgyfalster** [IPCC-WG1/Atlas#46]
When the map projection is set to 'Robinson (Pacific-centric)' and then the map is exported to a PNG file, polygon edges from continents touching the bounding box cross from one edge to the other.

**To Reproduce**
1. Set map projection to Robinson (Pacific-centric)
2. Download map as PNG

**Expected behavior**
For the exported map to look as it does in the browser viewer. 

**Screenshots**
![CMIP6 - Mean temperature (T) Change deg C - Warming 2°C SSP2 4 5 (rel  to 1961-1990) - Annual (34 models) (1)](https://user-images.githubusercontent.com/31246704/128906534-02de2b1f-10fb-4642-8dea-5118961cbd07.png)

**Desktop (please complete the following information):**

- OS: Windows
 - Browser: Chrome
 - Version: 92.0.4515.131

**Comment by jesusff** [comment]
Thank you for reporting. This has been solved in the new Interactive Atlas version, to be released on Sep 27th
