### ISSUE TITLE
Mislabeled River Basin in Atlas

### ISSUE THREAD

**Issue by aphilp12** [IPCC-WG1/Atlas#47]
A Canadian river basin is mislabeled as a region. It is labeled as South Asia,  This is in the regional information area.  I have attached a screenshot of the error.  All regional basins should be checked for accuracy.  

![Atlas_Label_Error](https://user-images.githubusercontent.com/88781189/129037499-20c93a0d-dea3-4ead-8d32-0949b30a78db.png)

**Comment by jesusff** [comment]
Thank you for reporting. This has been solved in the new Interactive Atlas version, to be released on Sep 27th
