### ISSUE TITLE
Point Information not accurate / consistent with map color bars

### ISSUE THREAD

**Issue by RH-UN** [IPCC-WG1/Atlas#49]
I am noticing that point inofrmation for the cursor position is sometimes (in some spots) not giving accurate values relative to point color and corresponding color bar value.

**Comment by jesusff** [comment]
Thank you for reporting. This has been solved in the new Interactive Atlas version, to be released on Sep 27th

**Comment by RH-UN** [comment]
Perfect ! Thanks.
________________________________
