### ISSUE TITLE
ATLAS review - Inventory names

### ISSUE THREAD

**Issue by JavierDiezSierra** [IPCC-WG1/Atlas#5]
I believe it would be appropriate to change the name of the inventory files included in the folder **ESGF -inventory** to better reflect the realm (atmos, land, ocean, etc) and the frequency of the subset.

**Comment by jesusff** [comment]
Thank you for the review. There is now a new structure, where this directory has been removed. This ESGF-inventory was a development product to check the availability of data at ESGF and to help in planning the final Atlas dataset. The final inventory of data used in the Atlas is under the `inventory` directory in the new structure
