### ISSUE TITLE
Default temperature colormap seems to be inconsistent

### ISSUE THREAD

**Issue by chogg** [IPCC-WG1/Atlas#50]
**Description of the problem**

The global temperature colormap plot initially shows the temperature distribution for 1.5degC but shows 2degC selected in the legend.

**To Reproduce**

1. Go to https://interactive-atlas.ipcc.ch/
2. Select 1.5 degC from the legend
3. Select 2 degC from the legend

**Expected behavior**
I expected to see a change in the colormap image when I initially select 1.5 degC (changing from the initial default of 2 degC), but the image stays the same. If I then select 2degC the colormap changes to a hotter image.

- OS: iOS
 - Browser Chrome
 
 
PS the tool looks very approachable. Thanks for the awesome work.

**Comment by chogg** [comment]
The 4degC button in the legend also seems to make no change to the temperature colormap. This is a different issue though.

**Comment by jesusff** [comment]
Thank you for reporting. This issue has been solved in the new Interactive Atlas, to be released on Sep 27th

**Comment by chogg** [comment]
Looks good now
