### ISSUE TITLE
https://interactive-atlas.ipcc.ch/permalink/UGjnbiTX

### ISSUE THREAD

**Issue by GENS-Tools** [IPCC-WG1/Atlas#51]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

**To Reproduce**

Write below the steps to reproduce the problem:

1. Dataset; model projection CMIP6
2. Set value and periods to 4 degrees C, SSP5 8.5, 1986-2005 
2. Choose variable; Consecutive Dry Days (CCD)

**Expected behavior**

When loading the map it stops and doesn't load the full map (see screenshot)

**Screenshots**

![image](https://user-images.githubusercontent.com/79167065/130580350-09ad5c6e-afc2-4343-8afe-3496687c4149.png)

**Desktop (please complete the following information):**

- OS: Windows
 - Browser; Google Chrome
 - Version: 92.0.4515.159

**Additional context**

--

**Comment by jesusff** [comment]
Thank you for your feedback. This was a temporary problem in one of our servers. The permalink works now.
