### ISSUE TITLE
failing to display a CDD change map with respect to the 1995-2015 baseline

### ISSUE THREAD

**Issue by pierolionello** [IPCC-WG1/Atlas#53]
I have selected CMIP6, CDD, 3°C GWL, baseline 1995-2014.  the error ref
https://interactive-atlas.ipcc.ch/permalink/yf8eyPRB
is reported and no map is displayed.

Selecting other baselines the problem is solved. It seems to be related to this specific baseline

Thanks for your help
Piero Lionello

 - Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

**To Reproduce**

Write below the steps to reproduce the problem:

1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jesusff** [comment]
Thank you for your feedback. This issue seems to be some temporary problem, since the map displays correctly at the moment.
