### ISSUE TITLE
CDD results map won't appear for global warming level 2C SSP5-8.5 relative to 1850-1900

### ISSUE THREAD

**Issue by srose16** [IPCC-WG1/Atlas#54]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

CDD results map won't appear for global warming level 2C SSP5-8.5 anomaly relative to 1850-1900. The global map in the interactive atlas is blank (all white). The maps for the other global warming levels are fine - 1.5C, 3C, and 4C.

**Comment by jesusff** [comment]
Thank you for your report. This was a temporary problem due to a request time out to the server. It usually works by retrying, as long as the browser cache is cleared. This cache problem has been reduced in the new version of the Interactive Atlas, to be released on Sep 27th.
