### ISSUE TITLE
The interactive atlas should be accessible with one click and should catch the eye on the main page

### ISSUE THREAD

**Issue by farukg** [IPCC-WG1/Atlas#55]
I came here after visiting the main page https://www.ipcc.ch/
the atlas is great, so it should not be hidden in deep links. People coming to the site need to see 

1. `eye-catching button labeled Interactive Atlas` which they can click without thinking and get to the map. 
2.  On the map its already nice to be able to look "if and how much my place would be affected". 
     Still same here:  `eye-catching input to change the warming value`. 

That way it would just take **[one search](https://www.google.com/search?q=ipcc) && 2 clicks [to see the own location fire](https://interactive-atlas.ipcc.ch/regional-information#eyJ0eXBlIjoiQVRMQVMiLCJjb21tb25zIjp7ImxhdCI6MTI5Njk0NSwibG5nIjotNTE2NTE0LCJ6b29tIjozLCJwcm9qIjoiRVBTRzo1NDAzMCJ9LCJwcmltYXJ5Ijp7InNjZW5hcmlvIjoic3NwNTg1IiwicGVyaW9kIjoiMiIsInNlYXNvbiI6InllYXIiLCJkYXRhc2V0IjoiQ01JUDYiLCJ2YXJpYWJsZSI6InRhcyIsInZhbHVlVHlwZSI6IkFOT01BTFkiLCJoYXRjaGluZyI6IlNJTVBMRSIsInJlZ2lvblNldCI6ImFyNiIsImJhc2VsaW5lIjoicHJlSW5kdXN0cmlhbCIsInJlZ2lvbnNTZWxlY3RlZCI6W119LCJwbG90Ijp7ImFjdGl2ZVRhYiI6InBsdW1lIiwibWFzayI6Im5vbmUiLCJzY2F0dGVyWU1hZyI6bnVsbCwic2NhdHRlcllWYXIiOm51bGwsInNob3dpbmciOmZhbHNlfX0=)**:fire:.:skull_and_crossbones:
People are lazy (that includes me too), if they weren't, we wouldnt need an atlas. I think this is crucial.

PS: honestly, at first i thought with interactive atlas that [rotating globe](https://interactive-atlas.ipcc.ch/) was meant, it would be a great pity when people get only so far!

**Comment by gutierjm** [comment]
Thank you very much for your feedback. 

The Interactive Atlas has two components: 1) regional information and 2) regional synthesis. We agree that the current layout is not intuitive to get quickly expanded information on the "climate futures" (illustrated with the spinning globe at the landing page). This would correspond to a particular configuration of the regional information component (selecting global warming levels, etc.). We are working to include a simplified view of the regional information component focusing on "climate futures". We may include two interfaces in the regional information component: simple (climate futures) and advanced; moreover we may include a "quick link" to the simple interface besides the spinning globe.
