### ISSUE TITLE
https://interactive-atlas.ipcc.ch/permalink/JFBSyizm

### ISSUE THREAD

**Issue by ramirosgv** [IPCC-WG1/Atlas#56]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

**To Reproduce**

Write below the steps to reproduce the problem:

1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jesusff** [comment]
Thank you for your feedback. This is solved in the new version of the Interactive Atlas, to be released on Sep 27th. Sea level rise plots are only available for biomes and small islands regions sets.

**Comment by gutierjm** [comment]
> Thank you for your feedback. This is solved in the new version of the Interactive Atlas, to be released on Sep 27th. Sea level rise plots are only available for biomes and small islands regions sets.

... and for the AR6 reference regions, so open-ocean regions can be selected.
