### ISSUE TITLE
Incorrect label: Australia vs Australasia

### ISSUE THREAD

**Issue by kevin-hennessy** [IPCC-WG1/Atlas#57]
Australasia data: In the Interactive Atlas, when you select "Regional information" then "WGII continental", this produces a global map - a drop-down menu of region names would be handy. When you click over Australia or New Zealand, both Australia and New Zealand are highlighted on the map. Therefore, the region is Australasia, consistent with the name of WGII Chapter 11.  If you then select any of the menu options such as "Time series" or "Table Summary",  the plots or data are incorrectly labeled Australia rather than Australasia.

**Comment by jesusff** [comment]
Thank you for your feedback. We'll look into it. I took the freedom to move your extremely long title text to the body of the comment.

**Comment by jesusff** [comment]
This was fixed in a new Interactive Atlas version, to be released on Sep 27th. Thank you for reporting!
