### ISSUE TITLE
Lower max temperatures for 4 C GWL than 3 C

### ISSUE THREAD

**Issue by kevin-hennessy** [IPCC-WG1/Atlas#58]
For all regions, it's weird that the 95th percentile maximum of daily maximum temperatures is lower for 4 C global warming than 3 C global warming - it should be the opposite!  Why does this occur?

**Comment by jesusff** [comment]
Thank you for your feedback, but we are unable to reproduce the results you report. Could you, please, provide further details (e.g. such as those requested in the [errata template](https://github.com/IPCC-WG1/Atlas/issues/new?labels=errata&template=problem-report.md))?

**Comment by kevin-hennessy** [comment]
Hi Jesus,

See the attached file.

Errata #58 is described with screenshots in the attached file.

Regards,

Kevin.
________________________________

**Comment by jesusff** [comment]
Dear Kevin, attachments in e-mail replies are currently ignored by github. Could you comment/attach files in the website? If you are reading this in your e-mail, it would be just a matter of following the "view it on Github" link at the bottom. Sorry for the inconvenience.

**Comment by kevin-hennessy** [comment]
[Data averaged over Australasia from the WG1 interactive atlas.docx](https://github.com/IPCC-WG1/Atlas/files/7241431/Data.averaged.over.Australasia.from.the.WG1.interactive.atlas.docx)
The attached file describes #57 (fixed) and #58 (outstanding).

**Comment by gutierjm** [comment]
The number of models reaching 4º is smaller than those reaching 3º (27 and 16, respectively; see https://github.com/IPCC-WG1/Atlas/tree/main/warming-levels for more information). As a result, the P5-P95 ranges could seem inconsistent, particularly when looking at absolute magnitudes where model biases affect the relative position of the models, independently on the particular climate sensitivities. Results are more consistent for changes, which is the recommended use for the climate dimension of Global Warming Levels. 

The plot below shows one of the examples above described (for TXx). The highlighted 11 models are those reaching 3º but not 4º. 

![image](https://user-images.githubusercontent.com/5774620/138619386-77f0ecf5-b4fe-4186-ab15-92e4ac4b2d85.png)

We recommend adding a note in results showing this apparent inconsistency: "Note that the ensembles for the different global warming levels are different and, therefore, ranges and percentiles are not directly comparable."
