### ISSUE TITLE
ATLAS review - Export PDF

### ISSUE THREAD

**Issue by JavierDiezSierra** [IPCC-WG1/Atlas#6]
The option "Export PDF" in the IA returns a file with a wrong extension (".png"). Besides, in my opinion, the name of the files are a little bit ambiguous since they contains several reference regions that have not been selected by the user:

`CMIP6 - Accumulated precipitation (PR) Relative change (mm_month) - Long Term (2081-2100) SSP5 8.5 AR5 (1986-2005) - Annual (Greenland_Iceland, E.Europe, S.Asia, Sahara, N.E.Canada, N.W.North-America, S.Central-America, C.Nor-1.png`

**Comment by jesusff** [comment]
Thank you for the review. We were not able to replicate the problem with the extension returned by the Export PDF in any browser. Could you provide more details on the specific selection with fails?

The naming of the files has been fixed. Thanks for reporting.
