### ISSUE TITLE
Missing NCA region in the Interactive ATLAS visualization: REGIONS (Central & South America)

### ISSUE THREAD

**Issue by TCavazos** [IPCC-WG1/Atlas#63]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

 NCA region is missing in the Interactive ATLAS visualization in: REGIONS (Central & South America). I'm using Google Chrome.

**To Reproduce**

Write below the steps to reproduce the problem:

1.  Go to  https://interactive-atlas.ipcc.ch/regional-synthesis#eyJ0eXBlIjoiQ0lEIiwic2VsZWN0ZWRJbmRleCI6WyJtZWFuX2Fpcl90ZW1wZXJhdHVyZSJdLCJzZWxlY3RlZFZhcmlhYmxlIjoiY29uZmlkZW5jZSIsInNlbGVjdGVkQ291bnRyeSI6IkdJQyIsIm1vZGUiOiJTVU1NQVJZIiwiY29tbW9ucyI6eyJsYXQiOjk3NzIsImxuZyI6NDAwNjkyLCJ6b29tIjo0LCJwcm9qIjoiRVBTRzo1NDAzMCIsIm1vZGUiOiJjb21wbGV0ZV9hdGxhcyJ9fQ==

2. Look at the list of Central and South America
3.  Before SCA it should appear NCA

**Expected behavior**

**Screenshots**
![ScreenShot_Interactive-Atlas](https://user-images.githubusercontent.com/18623407/134788633-445d0688-6ccd-4405-84aa-05eedb75e548.jpg)

**Desktop (please complete the following information):**

 - Browser [e.g. chrome, safari]: Google CHROME

**Additional context**

**Comment by gutierjm** [comment]
The organization in the Interactive Atlas regional synthesis follows that of Table TS.5. North Central is included in North America in this table.
