### ISSUE TITLE
Looking for map color scale definitions

### ISSUE THREAD

**Issue by turban** [IPCC-WG1/Atlas#69]
I'm looking for the map color scale definitions used in the interactive atlas. Are they included in this repo? I would like to use the GeoTIFFs to recreate similar looking maps as shown in the atlas, and need to know which colors to apply.

**Comment by jesusff** [comment]
Dear @turban,

the Interactive Atlas follows the official IPCC color scales that you can find here https://github.com/IPCC-WG1/colormaps. Note, however, that the Interactive figures are subject to the IPCC copyright (permission is only granted to use the material exactly as it is and figures cannot be altered in any way), whereas the underlying data is distributed with an open license (as CC-BY). A very accurate replication of the figures might look like a derivative work of the original figures, so we highly encourage you to use the original figures as exported by the Interactive Atlas.

https://interactive-atlas.ipcc.ch/license
