### ISSUE TITLE
Broken elements on front page (video & testing survey)

### ISSUE THREAD

**Issue by markwmuller** [IPCC-WG1/Atlas#70]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

There are two videos on the page https://interactive-atlas.ipcc.ch/ which show "This video does not exist". Moreover, there is a survey link greyed out. 

**To Reproduce**

go to https://interactive-atlas.ipcc.ch/

**Expected behavior**

The landing page should not have broken elements. 

**Screenshots**

![image](https://user-images.githubusercontent.com/3056063/139965301-aeddc4d1-6805-4cac-b5ac-17433bedb49c.png)

**Desktop (please complete the following information):**

- OS: Linux (Ubuntu 20.04)
 - Browser Firefox 93 and Chromium 95.0

**Comment by rosannaamato** [comment]
Hi, I had hoped to use the embedded videos in some training tomorrow morning (9am UTC 03/11/2021). If it's possible for these links to be fixed today, that would be a huge help!

**Comment by jesusff** [comment]
Thank you for reporting. The videos are back now. They were temporarily unavailable from the streaming platform used. Unfortunately, the user testing survey is not yet ready. Thus, the greyed out link.

**Comment by markwmuller** [comment]
Thanks for your work here. The atlas is an amazing tool.

**Comment by rosannaamato** [comment]
Thank you so much! Excellent resource and communication :D
