### ISSUE TITLE
Empty .nc files downolads

### ISSUE THREAD

**Issue by Vicencmolto** [IPCC-WG1/Atlas#71]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

Empty .nc file downolads

**To Reproduce**

Write below the steps to reproduce the problem:

We have detected this errata with the CORDEX Mediterranean projections products. As an Example: Select Cordex Mediterranean projection, variable sea surface temperature, scenario RCP4.5, period "medium term", Value (deg C) and season: customized season january to january (monthly data) and download as .nc file

**Expected behavior**

To download a netcdf file with the data product but it download an empty (0Kb) file instead

**Screenshots**

**Desktop (please complete the following information):**

- OS: -
 - Browser: Google Chrome
 - Version 95.0.4638.69 (Build oficial) (64 bits)

**Additional context**

**Comment by rosannaamato** [comment]
I have the same issue. Encountered when trying to download e.g. CMIP6 - Mean temperature (T) deg C - Long Term (2081-2100) SSP5-8.5 (rel. to 1986-2005) - Annual (34 models) Regions: South and Southeast Asian monsoon

**Comment by oceandiscovery** [comment]
Hello

The platform is returning empty netCDF (*.nc) files in many of the requested model/product combinations. I give here an example of reproducibility of the error, but it is not the only case, it is happening in many of the requested combinations.

**Request for:**
CORDEX Mediterranean - Sea Surface Temperature (SST) deg C - Near Term (2021-2040) RCP4.5 (rel. to 1995-2014) - Annual (4 models).
**Result:**
NetCDF File length = 0

**Comment by jesusff** [comment]
Thank you all for reporting. We are working to solve it as soon as possible. This problem raised when fixing #67 . It seems that the problem affects all requests for Quantity: Value, regardless of all other selections.

**Comment by mokhodge** [comment]
I also encounter this issue for surface pH CMIP6 projections (value).

**Comment by gutierjm** [comment]
Fixed in the version published on 21 December 2021. Please let us know if you find any other problems.
