### ISSUE TITLE
Is source code available for the atlas itself?

### ISSUE THREAD

**Issue by Peter9192** [IPCC-WG1/Atlas#72]
I'm quite impressed by the IPCC interactive atlas. I think this way of sharing climate information is very accessible and should be done more often. Therefore, I was wondering if the source code for the atlas itself is available, or documented somewhere. I think it would be great if (some of) it can be reused.

**Comment by jesusff** [comment]
Thanks for your interest, Peter. Unfortunately, the source code for the Interactive Atlas itself is not open for the moment. It is a mixture of open technologies which are described in this post https://predictia.es/en/news/Open-Source-FAIR-Technology-Interactive-Atlas-IPCC We are working to provide further documentation on the technological background behind the Interactive Atlas.

**Comment by Peter9192** [comment]
Thanks for the reply, the blogpost looks very helpful already. Feel free to close this issue or leave it open if you want to update us when more documentation comes available 👍
