### ISSUE TITLE
CID checklist variable name updates

### ISSUE THREAD

**Issue by AlexRuane** [IPCC-WG1/Atlas#74]
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

The "Ocean and lake acidity" climatic impact-driver should be just "Ocean acidity"

**To Reproduce**

Write below the steps to reproduce the problem:

1. Open Interactive Atlas
2. Click on Regional Synthesis
3. Examine list of CIDs in checklist portion on left side

**Expected behavior**

List of CIDs should be consistent with final IPCC WGI list of CIDs in Table 12.1 and WGI SPM Figure SPM.9.  "Ocean and lake acidity" should be just "Ocean acidity"

**Screenshots**

![image](https://user-images.githubusercontent.com/96098319/145929616-cb1df23d-ef48-411c-811c-b8650bf1b3da.png)

**Desktop (please complete the following information):**

- OS: Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] Chrome 96.0.4664.45

**Additional context**

**Comment by gutierjm** [comment]
The labels do not affect the results or the exported products, so this is not considered an errata. Therefore, this will be fixed in a future update to align with Figure SPM.9. In addition to this, the label "Mean air temperature" will be changed to "Mean surface temperature" for the same reason.

**Comment by gutierjm** [comment]
Fixed in the version published on 21 December 2021
