### ISSUE TITLE
ATLAS review - code comments, license and author information

### ISSUE THREAD

**Issue by jesusff** [IPCC-WG1/Atlas#8]
Jupyter notebooks are a great way to explain in detail examples of use of the available data and scripts. However, I think that scripts could be further commented to improve reusability. At least the main sections and some specific actions. E.g. there are hardcoded specific model runs excluded from the computations here:
https://github.com/IPCC-WG1/Atlas/blob/73961c43adb2a55394da862350333b301af46d2f/aggregated-datasets/scripts/computeDeltas.R#L73 . While transparent, because the code is open, a comment line stating why these runs are excluded would be in order.

Also, given that the scripts are devoted to reusability, all of them should include a license text and author(s). I also miss the author(s) in notebooks.

**Comment by hot007** [comment]
Also, some scripts contain commented out code, e.g. [AtlasCDOremappeR_CMIP.sh](https://github.com/IPCC-WG1/Atlas/blob/master/scripts/ATLAS-data/bash-interpolation-scripts/AtlasCDOremappeR_CMIP.sh), which e.g. shows different methods for gap filling, but I'm not sure if these are provided as options for the user, or if it is dis-used code. More clarity would be good, or commented code removed.

**Comment by jesusff** [comment]
Scripts comments have generally improved, avoiding commented-out code. Also, they share now a common header with license, author and description.
