### ISSUE TITLE
Exporting uncertainty layers together with the data underlying the maps as NetCDF

### ISSUE THREAD

**Issue by gutierjm** [IPCC-WG1/Atlas#80]
The Interactive Atlas  allows downloading the data underlying the figures (maps) as GeoTiff and NetCDF files. However, the uncertainty information (either simple or advanced) is not available for download, thus limiting the use of the data. 

Posted by the Atlas support team, building on several comments/requests received from users.

**Comment by gutierjm** [comment]
We are working to enhance the downloading facilities so both data and uncertainty (the layers needed to define the simple/advance approaches, as selected in the uncertainty interface) are exported as a zipped file with the NetCDF option. If no uncertainty is selected/displayed the export option will continue exporting the data alone. Moreover, GeoTiff will continue exporting only the data in all cases.

This will be deployed in future versions.

**Comment by kushankb** [comment]
Hi there! I am wondering if this issue has been resolved? I can't see an option to export the data as a zipped file which includes both the data and uncertainty layer. I am wondering when can we expect this? It would definitely make the data more useable. Many thanks!

**Comment by helgegoessling** [comment]
I completely agree, this feature would be really great to have!

**Comment by Cleartypee** [comment]
+1, this would be extremely useful.

**Comment by sadielbartholomew** [comment]
I would find this feature really useful, also (I can came here to the Issue Tracker to request this but saw this Issue was already open to document the feature request).

**Comment by gutierjm** [comment]
This new functionality has been included in the version just deployed (IA_Fixed_Dec2024). The active uncertainty layer (if any) is now exported together with the underlying data (in a zipped file).
