### ISSUE TITLE
Batch download option?

### ISSUE THREAD

**Issue by Cleartypee** [IPCC-WG1/Atlas#91]
Firstly, I love this tool. I am wondering, however, if there is any functionality that enables users to download multiple spatial layers quickly? e.g. downloading all variables for three timeframes and two scenarios looks like it means manually downloading 162 files one at a time via the export function. If not, this would be a drastic improvement.

Thank you

**Comment by jesusff** [comment]
Thank you for the suggestion. Unfortunately, there is currently no public API to automate this process.
